# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: Set up Go
description: Set up Go

outputs:
  go-version:
    description: Resolved Go version from setup environment
    value: ${{ steps.setup-go.outputs.go-version }}

runs:
  using: composite
  steps:
    - name: Set up Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      id: setup-go
      with:
        go-version-file: "go.mod"
        cache: true
