# Visit https://golangci-lint.run/ for usage documentation
# and information on other useful linters
issues:
  max-same-issues: 0

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - goheader
    - goimports
    - nolintlint
    - testifylint
    - whitespace
    - errorlint
