# Copyright 2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

[tools]
go = "1.26.5"
hk = "1.56.1"
golangci-lint = "2.13.1"
"aqua:google/addlicense" = "1.2.0"
opentofu = "1.12.6"
terraform = "1.15.9"
k3d = "5.9.0"
"aqua:defenseunicorns/uds-cli" = "0.36.0"

[env]
MISE_USE_VERSIONS_HOST_TRACK = "0"
TF_CLI_CONFIG_FILE = "{{ config_root }}/.tofurc.dev"
