# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: Nightly Release
on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *" ## nightly at 3am UTC

permissions:
  contents: read

jobs:
  test:
    uses: ./.github/workflows/test-acc.yaml

  push:
    runs-on: ubuntu-latest
    environment: release-nightly
    needs: test
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-tags: 'true'

      - name: Setup golang
        uses: ./.github/actions/setup-golang

      - name: Update nightly-unstable tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
        run: |
          # A previous release was created using a lightweight tag
          # git describe by default includes only annotated tags
          # git describe --tags includes lightweight tags as well
          DESCRIBE=`git tag -l --sort=-v:refname | grep -v nightly | head -n 1`
          MAJOR_VERSION=`echo $DESCRIBE | awk '{split($0,a,"."); print a[1]}'`
          MINOR_VERSION=`echo $DESCRIBE | awk '{split($0,a,"."); print a[2]}'`
          MINOR_VERSION="$((${MINOR_VERSION} + 1))"
          TAG="${MAJOR_VERSION}.${MINOR_VERSION}.0-nightly"
          # cleanup old release
          gh release delete ${TAG} --cleanup-tag -y || true
          # generate new release
          DATE="$(date +'%Y%m%d')"
          gh release create \
            -t "${TAG}" \
            --prerelease \
            -n "Nightly unstable build: $DATE"
