# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

# Terraform Provider release workflow.
name: Release

# This GitHub action creates a release when a tag that matches the pattern
# "v*" (e.g. v0.1.0) is created or when triggered by another workflow.
on:
  push:
    tags:
      - "v*"
  workflow_call:
    inputs:
      tag_name:
        required: false
        type: string
        description: "The tag name to use for the release"
    secrets:
      UDS_REGISTRY_USER:
        required: true
        description: "Username for UDS registry authentication"
      UDS_REGISTRY_TOKEN:
        required: true
        description: "Token for UDS registry authentication"

permissions: {}

concurrency:
  group: release-${{ inputs.tag_name || github.ref }}
  cancel-in-progress: false

jobs:
  goreleaser:
    name: Build and publish release
    runs-on: uds-ubuntu-big-boy-4-core
    timeout-minutes: 60 # Match the timeout in the goreleaser command
    permissions:
      contents: write # Required by GoReleaser to create the GitHub release.
      packages: write # Required to publish the provider to GHCR.
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ inputs.tag_name || github.ref }}
          # Allow goreleaser to access older tag information
          fetch-depth: 0
          fetch-tags: true
          persist-credentials: false

      - name: Setup golang
        uses: ./.github/actions/setup-golang

      - name: Install syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      # - name: Import GPG key
      #   uses: crazy-max/ghaction-import-gpg@cb9bde2e2525e640591a934b1fd28eef1dcaf5e5 # v6.2.0
      #   id: import_gpg
      #   with:
      #     gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
      #     passphrase: ${{ secrets.PASSPHRASE }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7.2.3
        with:
          args: release --clean --timeout 60m
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOTMPDIR: ${{ runner.temp }}
          # GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}

      - name: Login to UDS Registry
        run: echo "$UDS_REGISTRY_TOKEN" | go tool oras login -u "$UDS_REGISTRY_USER" --password-stdin registry.defenseunicorns.com
        env:
          UDS_REGISTRY_USER: ${{ secrets.UDS_REGISTRY_USER }}
          UDS_REGISTRY_TOKEN: ${{ secrets.UDS_REGISTRY_TOKEN }}

      - name: Login to GHCR
        env:
          GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GHCR_USER: ${{ github.actor }}
        run: echo "$GHCR_TOKEN" | go tool oras login -u "$GHCR_USER" --password-stdin ghcr.io

      # https://github.com/opentofu/opentofu/blob/main/website/docs/cli/oci_registries/provider-mirror.mdx
      - name: Publish to OCI Registries
        shell: bash
        working-directory: dist
        env:
          GHCR_NAMESPACE: ${{ github.repository_owner }}
        run: |
          set -euo pipefail

          layout="tmp-layout"

          cleanup() {
              rm -rf "$layout"
          }

          trap cleanup EXIT

          mkdir "$layout"

          index_mediatype="application/vnd.opentofu.provider"
          manifest_mediatype="application/vnd.opentofu.provider-target"
          layer_mediatype="archive/zip"

          find . -name "*.zip" -printf "%f\n" | while read -r archive; do
              entry=$(jq ".[] | select(.name == \"${archive}\")" artifacts.json)
              os_arch=$(echo "$entry" | jq -r '"\(.goos)_\(.goarch)"')

              go tool oras push \
                --artifact-type "$manifest_mediatype" \
                --oci-layout "$layout:$os_arch" \
                "$archive:$layer_mediatype"
          done

          index="$layout/index.json"
          name=$(jq -r .project_name metadata.json)
          version=$(jq -r .version metadata.json)
          index_to_tag="${name}_$version.json"

          jq --arg mediatype "$index_mediatype" '
            .artifactType = $mediatype |
            .manifests = (.manifests | map(
              if .annotations."org.opencontainers.image.ref.name" then
                . + {
                  platform: {
                    os: (.annotations."org.opencontainers.image.ref.name" | split("_")[0]),
                    architecture: (.annotations."org.opencontainers.image.ref.name" | split("_")[1])
                  }
                }
              else
                .
              end
            ))
          ' "$index" > "$index_to_tag"

          go tool oras manifest push --oci-layout "$layout:$version" "$index_to_tag"

          # Publish to UDS registry
          uds_registry_url="registry.defenseunicorns.com/ops/$name"
          go tool oras cp --from-oci-layout "$layout:$version" "$uds_registry_url:$version"

          # Publish to GHCR
          namespace="$GHCR_NAMESPACE"
          type_name="${name#terraform-provider-}"
          ghcr_url="ghcr.io/$GHCR_NAMESPACE/opentofu-providers/$namespace/$type_name"
          go tool oras cp --from-oci-layout "$layout:$version" "$ghcr_url:$version"

      - name: Upload release assets (if any failed)
        if: failure()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: goreleaser-dist
          path: dist/
          retention-days: 5
