# Copyright 2025-2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: Test
on:
  workflow_call: # allow other workflows to call this one
  pull_request:
    # milestoned is added here as a workaround for release-please not triggering PR workflows (PRs should be added to a milestone to trigger the workflow).
    types: [milestoned, opened, reopened, synchronize]
    # Keep these paths aligned with the code filter in docs-shim.yaml.
    paths-ignore:
      - "**.md"
      - "**.jpg"
      - "**.png"
      - "**.gif"
      - "**.svg"
      - ".gitignore"
      - ".vscode/**"
      - "CODEOWNERS"
      - "LICENSE"

permissions:
  contents: read

# Abort prior jobs in the same workflow / PR
concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: uds-ubuntu-big-boy-4-core
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959e # v4.2.0
        with:
          # renovate: datasource=github-releases depName=jdx/mise versioning=semver
          version: 2026.7.0
          install: true
          cache: true
      - name: Lint
        run: mise exec -- uds run lint:check

  e2e:
    name: E2E tests
    runs-on: uds-ubuntu-big-boy-4-core
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959e # v4.2.0
        with:
          # renovate: datasource=github-releases depName=jdx/mise versioning=semver
          version: 2026.7.0
          install: true
          cache: true

      - name: E2E tests
        run: mise exec -- uds run e2e

      - name: Save Logs
        uses: defenseunicorns/uds-core/.github/actions/save-logs@bd1f2e4acdb2945ac1887e81668227291f183018
        if: always()
        with:
          suffix: e2e

  unit:
    name: Unit tests
    runs-on: uds-ubuntu-big-boy-4-core
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959e # v4.2.0
        with:
          # renovate: datasource=github-releases depName=jdx/mise versioning=semver
          version: 2026.7.0
          install: true
          cache: true

      - name: Unit tests
        run: mise exec -- uds run test-unit
