# Copyright 2025 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: Test
on:
  workflow_call: # allow other workflows to call this one
  pull_request:
    # milestoned is added here as a workaround for release-please not triggering PR workflows (PRs should be added to a milestone to trigger the workflow).
    types: [milestoned, opened, reopened, synchronize]
    paths-ignore:
      - "**.md"
      - "**.jpg"
      - "**.png"
      - "**.gif"
      - "**.svg"
      - "**.tf"
      - "adr/**"
      - "docs/**"
      - "CODEOWNERS"
      - "goreleaser.yml"

permissions:
  contents: read

# Abort prior jobs in the same workflow / PR
concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: uds-ubuntu-big-boy-4-core
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: ./.github/actions/setup-golang
      - name: golangci-lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
        with:
          version: latest

  acceptance:
    runs-on: uds-ubuntu-big-boy-4-core
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install UDS CLI
        uses: defenseunicorns/setup-uds@ab842abcad1f7a3305c2538e3dd1950d0daacfa5 # v1.0.1
        with:
          # renovate: datasource=github-tags depName=defenseunicorns/uds-cli versioning=semver
          version: v0.34.2

      - name: Install k3d
        shell: bash
        # renovate: datasource=github-tags depName=k3d-io/k3d versioning=semver
        run: curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | TAG=v5.9.0 bash

      - name: Setup golang
        uses: ./.github/actions/setup-golang

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@a1320f892987e89d278cc92dc5adc984fb93aca4 # v2.0.2
        with:
          # renovate: datasource=github-tags depName=opentofu/opentofu versioning=semver
          tofu_version: v1.12.4
          tofu_wrapper: false

      - name: Run acceptance tests
        run: uds run test-acc

      - name: Save Logs
        uses: defenseunicorns/uds-core/.github/actions/save-logs@bd1f2e4acdb2945ac1887e81668227291f183018
        if: always()
        with:
          suffix: acc

  unit:
    runs-on: uds-ubuntu-big-boy-4-core
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install UDS CLI
        uses: defenseunicorns/setup-uds@ab842abcad1f7a3305c2538e3dd1950d0daacfa5 # v1.0.1
        with:
          # renovate: datasource=github-tags depName=defenseunicorns/uds-cli versioning=semver
          version: v0.34.2

      - name: Setup golang
        uses: ./.github/actions/setup-golang

      - name: Run unit tests
        run: uds run test-unit

      - name: Save Logs
        uses: defenseunicorns/uds-core/.github/actions/save-logs@bd1f2e4acdb2945ac1887e81668227291f183018
        if: always()
        with:
          suffix: unit
